import Database from "better-sqlite3";
import { and, asc, desc, eq, sql } from "drizzle-orm";
import { drizzle } from "drizzle-orm/better-sqlite3";
import { destinations } from "@/features/trip/catalog";
import type { Budget, ItineraryItem, MutationSource, Trip, TripPreferences, TripSummary } from "@/features/trip/types";
import { budgets, candidates, itinerary, trips } from "../db/schema";
import { TripError } from "./errors";

const ddl = `PRAGMA foreign_keys=ON; CREATE TABLE IF NOT EXISTS trips(id TEXT PRIMARY KEY,destination TEXT,start_date TEXT,end_date TEXT,travelers INTEGER NOT NULL DEFAULT 2,interests_json TEXT NOT NULL DEFAULT '[]',budget_limit INTEGER,focused_destination_id TEXT,version INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS trip_candidates(trip_id TEXT NOT NULL REFERENCES trips(id) ON DELETE CASCADE,destination_id TEXT NOT NULL,source TEXT NOT NULL,position INTEGER NOT NULL,PRIMARY KEY(trip_id,destination_id)); CREATE TABLE IF NOT EXISTS itinerary_items(id TEXT PRIMARY KEY,trip_id TEXT NOT NULL REFERENCES trips(id) ON DELETE CASCADE,day INTEGER NOT NULL,position INTEGER NOT NULL,time TEXT NOT NULL,title TEXT NOT NULL,location TEXT NOT NULL,note TEXT NOT NULL,estimated_cost INTEGER NOT NULL,source TEXT NOT NULL); CREATE TABLE IF NOT EXISTS trip_budgets(trip_id TEXT PRIMARY KEY REFERENCES trips(id) ON DELETE CASCADE,transport INTEGER NOT NULL DEFAULT 0,stay INTEGER NOT NULL DEFAULT 0,food INTEGER NOT NULL DEFAULT 0,activities INTEGER NOT NULL DEFAULT 0);`;

export function createTripService(path = process.env.TRIP_DB_PATH ?? "data/trips.sqlite") {
  const sqlite = new Database(path); sqlite.exec(ddl); const db = drizzle(sqlite);
  const getTrip = (id: string): Trip => { const row = db.select().from(trips).where(eq(trips.id,id)).get(); if(!row) throw new TripError("NOT_FOUND","旅行が見つかりません"); const budget = db.select().from(budgets).where(eq(budgets.tripId,id)).get()!; const cs=db.select().from(candidates).where(eq(candidates.tripId,id)).orderBy(asc(candidates.position)).all(); const items=db.select().from(itinerary).where(eq(itinerary.tripId,id)).orderBy(asc(itinerary.day),asc(itinerary.position)).all(); return { id,version:row.version,preferences:{destination:row.destination??undefined,dates:row.startDate&&row.endDate?{start:row.startDate,end:row.endDate}:undefined,travelers:row.travelers,interests:JSON.parse(row.interestsJson),budgetLimit:row.budgetLimit??undefined},candidates:cs.flatMap(c=>{const d=destinations.find(x=>x.id===c.destinationId);return d?[{...d,source:c.source,position:c.position}]:[]}),focusedDestinationId:row.focusedDestinationId??undefined,itinerary:items.map(i=>({id:i.id,day:i.day,time:i.time,title:i.title,location:i.location,note:i.note,estimatedCost:i.estimatedCost,source:i.source,position:i.position})),budget:{transport:budget.transport,stay:budget.stay,food:budget.food,activities:budget.activities},createdAt:row.createdAt,updatedAt:row.updatedAt}; };
  const bump=(id:string,version:number)=>{const now=new Date().toISOString();const result=db.update(trips).set({version:sql`${trips.version}+1`,updatedAt:now}).where(and(eq(trips.id,id),eq(trips.version,version))).run();if(result.changes===0){let latest:Trip|undefined;try{latest=getTrip(id)}catch{}throw new TripError(latest?"VERSION_CONFLICT":"NOT_FOUND",latest?"旅行が更新されています":"旅行が見つかりません",latest)}};
  const tx=<T>(fn:()=>T)=>sqlite.transaction(fn)();
  const createTrip=()=>tx(()=>{const id=crypto.randomUUID(),now=new Date().toISOString();db.insert(trips).values({id,createdAt:now,updatedAt:now}).run();db.insert(budgets).values({tripId:id}).run();return getTrip(id)});
  const listTrips=():TripSummary[]=>db.select().from(trips).orderBy(desc(trips.updatedAt)).all().map(row=>({id:row.id,destination:row.destination??undefined,dates:row.startDate&&row.endDate?{start:row.startDate,end:row.endDate}:undefined,travelers:row.travelers,budgetLimit:row.budgetLimit??undefined,itineraryCount:db.select({count:sql<number>`count(*)`}).from(itinerary).where(eq(itinerary.tripId,row.id)).get()!.count,updatedAt:row.updatedAt}));
  const deleteTrip=(id:string)=>tx(()=>{const result=db.delete(trips).where(eq(trips.id,id)).run();if(!result.changes)throw new TripError("NOT_FOUND","旅行が見つかりません")});
  const updatePreferences=(input:{tripId:string;version:number;source:MutationSource}&Partial<TripPreferences>)=>tx(()=>{bump(input.tripId,input.version);const current=getTrip(input.tripId).preferences;const dates=input.dates===undefined?current.dates:input.dates;db.update(trips).set({destination:input.destination??current.destination??null,startDate:dates?.start??null,endDate:dates?.end??null,travelers:input.travelers??current.travelers,interestsJson:JSON.stringify(input.interests??current.interests),budgetLimit:input.budgetLimit??current.budgetLimit??null}).where(eq(trips.id,input.tripId)).run();return getTrip(input.tripId)});
  const updateBudget=(input:{tripId:string;version:number;source:MutationSource}&Partial<Budget>)=>tx(()=>{bump(input.tripId,input.version);db.update(budgets).set({transport:input.transport,stay:input.stay,food:input.food,activities:input.activities}).where(eq(budgets.tripId,input.tripId)).run();return getTrip(input.tripId)});
  const searchCandidates=(input:{tripId:string;version:number;source:MutationSource;interests:string[];season?:string;maxDailyCost?:number})=>tx(()=>{bump(input.tripId,input.version);const ranked=destinations.filter(d=>!input.maxDailyCost||d.estimatedDailyCost<=input.maxDailyCost).sort((a,b)=>input.interests.filter(i=>b.interests.includes(i)).length-input.interests.filter(i=>a.interests.includes(i)).length).slice(0,3);db.delete(candidates).where(eq(candidates.tripId,input.tripId)).run();if(ranked.length)db.insert(candidates).values(ranked.map((d,position)=>({tripId:input.tripId,destinationId:d.id,source:input.source,position}))).run();return getTrip(input.tripId)});
  const selectCandidate=(input:{tripId:string;version:number;source:MutationSource;destinationId?:string})=>tx(()=>{bump(input.tripId,input.version);if(input.destinationId&&!getTrip(input.tripId).candidates.some(c=>c.id===input.destinationId))throw new TripError("INVALID","候補にない旅行先です");db.update(trips).set({focusedDestinationId:input.destinationId??null}).where(eq(trips.id,input.tripId)).run();return getTrip(input.tripId)});
  const createItineraryItem=(input:{tripId:string;version:number;source:MutationSource}&Omit<ItineraryItem,"id">)=>tx(()=>{bump(input.tripId,input.version);const position=db.select({n:sql<number>`count(*)`}).from(itinerary).where(and(eq(itinerary.tripId,input.tripId),eq(itinerary.day,input.day))).get()!.n;db.insert(itinerary).values({...input,id:crypto.randomUUID(),position}).run();return getTrip(input.tripId)});
  const updateItineraryItem=(input:{tripId:string;itemId:string;version:number;source:MutationSource}&Partial<Omit<ItineraryItem,"id">>)=>tx(()=>{bump(input.tripId,input.version);const changes={day:input.day,time:input.time,title:input.title,location:input.location,note:input.note,estimatedCost:input.estimatedCost};const result=db.update(itinerary).set(changes).where(and(eq(itinerary.tripId,input.tripId),eq(itinerary.id,input.itemId))).run();if(!result.changes)throw new TripError("NOT_FOUND","予定が見つかりません");return getTrip(input.tripId)});
  const deleteItineraryItem=(input:{tripId:string;itemId:string;version:number;source:MutationSource})=>tx(()=>{bump(input.tripId,input.version);const result=db.delete(itinerary).where(and(eq(itinerary.tripId,input.tripId),eq(itinerary.id,input.itemId))).run();if(!result.changes)throw new TripError("NOT_FOUND","予定が見つかりません");return getTrip(input.tripId)});
  const reorderItinerary=(input:{tripId:string;version:number;source:MutationSource;items:{id:string;day:number;position:number}[]})=>tx(()=>{bump(input.tripId,input.version);input.items.forEach(x=>db.update(itinerary).set({day:x.day,position:x.position}).where(and(eq(itinerary.tripId,input.tripId),eq(itinerary.id,x.id))).run());return getTrip(input.tripId)});
  return {createTrip,listTrips,deleteTrip,getTrip,updatePreferences,updateBudget,searchCandidates,selectCandidate,createItineraryItem,updateItineraryItem,deleteItineraryItem,reorderItinerary,close:()=>sqlite.close()};
}

export type TripService=ReturnType<typeof createTripService>;
