
cc_binary(
    name = "hello_world",
    deps = ["@com_google_absl//absl/strings"],
    srcs = ["hello_world.cc"],
)

cc_binary(
    name = "play_view",
    deps = ["@com_google_absl//absl/strings",
            "@com_google_absl//absl/status:statusor"],
    srcs = ["play_view.cc"]
)